"""AgentProfile

Revision ID: 60b84f456237
Revises: 0969845611cf
Create Date: 2026-08-19 00:43:47.536745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60b84f456237'
down_revision = '0969845611cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('instagram', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_profiles_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_profiles_name'))

    op.drop_table('agent_profiles')
    # ### end Alembic commands ###
