"""add exclusive_collection table

Revision ID: 79c967db1fee
Revises: 90ba97e1190b
Create Date: 2026-08-16 22:48:47.454323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79c967db1fee'
down_revision = '90ba97e1190b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exclusive_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.String(length=36), nullable=False),
    sa.Column('cover_url', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exclusive_collection')
    # ### end Alembic commands ###
