"""initial: tabela de imoveis

Revision ID: 90ba97e1190b
Revises: 
Create Date: 2026-08-16 22:20:33.774031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90ba97e1190b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('subtype', sa.String(length=100), nullable=True),
    sa.Column('purpose', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('condo_fee', sa.Float(), nullable=True),
    sa.Column('iptu', sa.Float(), nullable=True),
    sa.Column('area', sa.Float(), nullable=True),
    sa.Column('area_total', sa.Float(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('suites', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('garage', sa.Integer(), nullable=True),
    sa.Column('garage_type', sa.String(length=100), nullable=True),
    sa.Column('solar_position', sa.String(length=50), nullable=True),
    sa.Column('floor_number', sa.String(length=50), nullable=True),
    sa.Column('total_floors', sa.Integer(), nullable=True),
    sa.Column('condominium_name', sa.String(length=255), nullable=True),
    sa.Column('is_financeable', sa.Boolean(), nullable=True),
    sa.Column('accepts_exchange', sa.Boolean(), nullable=True),
    sa.Column('furnished', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('neighborhood', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('badge', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amenities_property', sa.Text(), nullable=True),
    sa.Column('amenities_condo', sa.Text(), nullable=True),
    sa.Column('amenities', sa.Text(), nullable=True),
    sa.Column('gallery', sa.Text(), nullable=True),
    sa.Column('agent', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('calculated_category', sa.String(length=50), nullable=True),
    sa.Column('is_exclusive', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_properties_area'), ['area'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_bedrooms'), ['bedrooms'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_neighborhood'), ['neighborhood'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_slug'), ['slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_properties_type'))
        batch_op.drop_index(batch_op.f('ix_properties_slug'))
        batch_op.drop_index(batch_op.f('ix_properties_reference'))
        batch_op.drop_index(batch_op.f('ix_properties_purpose'))
        batch_op.drop_index(batch_op.f('ix_properties_price'))
        batch_op.drop_index(batch_op.f('ix_properties_neighborhood'))
        batch_op.drop_index(batch_op.f('ix_properties_city'))
        batch_op.drop_index(batch_op.f('ix_properties_bedrooms'))
        batch_op.drop_index(batch_op.f('ix_properties_area'))

    op.drop_table('properties')
    # ### end Alembic commands ###
